### ISSUE TITLE
We need a new disclaimer regarding invoices from Germany

### ISSUE THREAD

**Issue by TheRealBro** [openSUSE/travel-support-program#100]
## Disclaimer
From now on, we need to supply the Finance department with original receipts from German invoices.

This is not needed, if the invoice comes in an electronic way to you, e.g. as PDF to your mailbox, than -of course- the PDF is sufficient to attach in the openSUSE TSP, but if you get a paper receipt from any organization (Hotel, petrol station, etc.) we need the original invoice as paper. 

Otherwise, the invoice is not accepted by the Finance department and the openSUSE TSP can not proceeded with the payment or reimbursement of this invoice. 

It is important to know that this applies to every invoice which comes out of Germany. So every transaction (business case) made in Germany which is invoiced to you not electronically but in paper and you want to reimburse via openSUSE TSP, you need to send the paper invoice to the following address.
Before you send in any invoice, please add it in the openSUSE TSP website and attach a photography / scan of the regarding invoice, that we can assign the paper invoice, which you sent in, to your openSUSE TSP account.

SUSE Linux GmbH
z.Hd. Katrin Murr
c/o openSUSE TSP
Maxfeldstr. 5
90409 Nürnberg
Germany

Thanks a lot for your support and your understanding of the changed process.
Unfortunately this new policy applies to everybody.

## End of disclaimer

Please make this Disclaimer available at the regarding part, where people file invoices in the openSUSE TSP.

**Comment by TheRealBro** [comment]
If you have questions regarding this issue, please refer to @Blondie7

:bowtie:

**Comment by cboltz** [comment]
Monika just told me that she no longer needs the paper invoices - closing as no-need-to-fix ;-)
