### ISSUE TITLE
Could be Ruby 2.5 causing a problem with creating events for tsp

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/travel-support-program#130]
Hi @hellcp I appear to be having an issue with creating new events for tsp.o.o. You can see the "Ask for" is not appearing. Only with the openSUSE Conference, which I put in a while back. I tried a few different things of switching take and creating new events, but it appears to just not work anymore. I think it would be a Ruby 2.5 issue again. Would you mind taking a look at it. @Conan-Kudo @ancorgs
![Screenshot from 2022-03-07 10-29-06](https://user-images.githubusercontent.com/8996626/157004381-580d0369-8dcf-4644-ae3b-9826dcb0855f.png)

**Comment by hellcp** [comment]
In events editor, there should be [request creation deadline](https://github.com/openSUSE/travel-support-program/blob/master/app/views/events/_form.html.haml#L13), is that still within date?

**Comment by ddemaio** [comment]
@hellcp yes, that's there. Need to put on my glasses I guess. Thank you.
