### ISSUE TITLE
In number_to_currency, unit being nil throws an error

### ISSUE THREAD

**Issue by hellcp** [openSUSE/travel-support-program#134]
This showed up as an issue in production:

```
ActionView::Template::Error (no implicit conversion of nil into String):
    101:                 - if expense.authorized_can_be_calculated?
    102:                   %td.authorized= number_to_currency("XX", :unit => expense.authorized_currency)
    103:                 - else
    104:                   %td.authorized= number_to_currency(e.text_field(:authorized_amount, :class => 'input-mini'), :unit => expense.authorized_currency)
    105: 
    106:   .well.col-md-12
    107:     = f.button :submit, :class => 'btn btn-primary'
```

https://github.com/openSUSE/travel-support-program/blob/339d53977dcd52954017be88e442134eea10ce5a/app/views/reimbursements/edit.html.haml#L104 needs to have `.to_s` added after `expense.authorized_currency`, but that's not exactly a good long term solution, we need to make sure there is a currency set for number_to_currency

**Comment by hellcp** [comment]
Also occurs in https://github.com/openSUSE/travel-support-program/blob/339d53977dcd52954017be88e442134eea10ce5a/app/views/reimbursements/show.html.haml#L63

**Comment by ddemaio** [comment]
Hi @hellcp & #syds Usually, I will let people know in the comments section what the 80% or adjusted amount will be. Or I email them. It would be cool to have that in the tool. It doesn't become exact since some values might have more than one currency and foreign exchange adjustments happen. We quote a currency value though, which tend to be quoted in EUR.

**Comment by hellcp** [comment]
That's not really what I'm asking, the issue in this ticket is that approved amount is not set in the travel sponsorship requests. My understanding is that you can't currently set that value within the UI, is that correct?

**Comment by ddemaio** [comment]
@hellcp that is correct. We used to be able to set the value, but it must have been about 3 or 4 years ago this option disappeared. I don't remember the exact time, but I'm sure for oSC19 it was working.

**Comment by hellcp** [comment]
I can fix it, but I feel like the entire permissions setup needs a bit of work

**Comment by hellcp** [comment]
I have patched our current production, adding a line:
```
can :approve, TravelSponsorship
```
in ability.rb, under supervisor permissions.

Please verify you can see [Set Amounts] button on travel sponsorships now.
