### ISSUE TITLE
Have a look at the permissions within the openSUSE instance

### ISSUE THREAD

**Issue by hellcp** [openSUSE/travel-support-program#152]
We have assigned most of the people who review tsp application the supervisor role, but maybe they should be assistants or tsp role instead? Let's see what limitations those roles have

**Comment by ddemaio** [comment]
Hi @hellcp looks like an update broke my admin access to approve and process the TSP. I'll need to make sure that the pdf form is generated (image example) as that is part of the process we've established with SUSE. 
![Screenshot from 2022-11-21 15-31-58](https://user-images.githubusercontent.com/8996626/203080692-4323b997-9a1d-4d43-a2fa-aa13bc750ca2.png)

**Comment by hellcp** [comment]
What exactly are you missing

**Comment by hellcp** [comment]
Resolved elsewhere, closing
