### ISSUE TITLE
decimal numbers are not saved when using a mysql2 database

### ISSUE THREAD

**Issue by tsdgeos** [openSUSE/travel-support-program#18]
If you make a request of 199.98 EUR it saves it as 199.00 if i am using the mysql2 backend and as 199.98 if i'm using the sqlite3 backend

**Comment by ancorgs** [comment]
I'll take a look this week. Thanks for testing it with MySQL.

**Comment by tsdgeos** [comment]
This seems to help https://github.com/openSUSE/travel-support-program/pull/20 no idea if it breaks sqlite or postgres

**Comment by ancorgs** [comment]
Fixed by fd0f95c5920cccd5631eb0dec055e02eacc83493. Thanks for reporting and spotting the cause.
