### ISSUE TITLE
Travel expenses report fails with mysql

### ISSUE THREAD

**Issue by tsdgeos** [openSUSE/travel-support-program#19]
It works with sqlite, but with mysql i get

Mysql2::Error: Every derived table must have its own alias: select count(*) as c from (SELECT sum(estimated_amount) AS sum_amount, estimated_currency AS sum_currency, event_id AS event_id, events.name AS event_name, events.country_code AS event_country, events.start_date AS event_start_date, events.end_date AS event_end_date FROM `request_expenses` INNER JOIN `requests` ON `requests`.`id` = `request_expenses`.`request_id` AND `requests`.`type` = 'TravelSponsorship' INNER JOIN `users` ON `users`.`id` = `requests`.`user_id` INNER JOIN `user_profiles` ON `user_profiles`.`user_id` = `users`.`id` INNER JOIN `events` ON `events`.`id` = `requests`.`event_id` LEFT JOIN reimbursements ON reimbursements.request_id = requests.id WHERE (estimated_amount IS NOT NULL) AND `requests`.`user_id` = 2 GROUP BY estimated_currency, event_id, events.name, events.country_code, events.start_date, events.end_date)

**Comment by ancorgs** [comment]
We only use PostgreSQL and SQLite, so this kind of things has been unnoticed so far. It's fine to have somebody testing the MySQL backend. I'll take a look next week to the issue.

**Comment by tsdgeos** [comment]
Thanks, my sql+ruby foo is quite small to try to guess what's wrong

**Comment by ancorgs** [comment]
I will upload a commit this afternoon fixing this issue and the 2 decimals one. I want to verify something else first.

**Comment by ancorgs** [comment]
I have not checked in the application itself, but according to the automated test suite, this should be fixed by fd0f95c5920cccd5631eb0dec055e02eacc83493.
