### ISSUE TITLE
Default sort order is "random"

### ISSUE THREAD

**Issue by cboltz** [openSUSE/travel-support-program#194]
https://tsp.opensuse.org/travel_sponsorships lists travel support requests in random order.

The headline indicates that the requests are sorted by ID (`Id ^`), but when looking at the list, the sorting is completely random. In my case, it is: 351, 197, 257, 80, 343, 148, 472, ...

At least, when reloading the page, I get the same order - but I don't have an idea which field might be used to get that order. None of the visible columns look "sorted".

To make things even more interesting: When i click on the `Id" header, I still get the same random order.

(Sorting based on `state` seems to work, but is not too useful.)

**Comment by cboltz** [comment]
Same problem on https://tsp.opensuse.org/reimbursements

**Comment by aryanvarma7272** [comment]
Hey @cboltz ,I am a very beginner , so can you please explain me in more simplified way or what has to be exactly done ?
