### ISSUE TITLE
Configure the available types of requests

### ISSUE THREAD

**Issue by ancorgs** [openSUSE/travel-support-program#21]
@tsdgeos This one is for you :wink: I saw in the diff you sent me that you also commented everything about merchandising shipment requests, because you don't use that feature. Thus I created this branch (which is actually branched from the `requester_is_not_a_role` branch already commented in the issue#17)
https://github.com/openSUSE/travel-support-program/tree/optional_requests

With that code, you can use the `config/site.yml` to disable the travel support requests or the shipment ones. Beware, as a consequence if the new feature, the format of that file has changed slightly, so take a look to the changes in `config/site.example.yml` if you are planing to reuse your old configuration.

When enabling/disabling types of requests, everything (even the user guide that is used as landing page) should adapt gracefully to the possible combinations (i.e. only travel support, only shipments or both).

So please review. If you are fine with the changes (in both issues/branches), I'll merge everything into master.

**Comment by tsdgeos** [comment]
looks good :)

**Comment by tsdgeos** [comment]
Should we close this too?

**Comment by ancorgs** [comment]
Right!
