### ISSUE TITLE
There's no way to reopen a cancelled reimbursemetn

### ISSUE THREAD

**Issue by tsdgeos** [openSUSE/travel-support-program#28]
If someone makes a mistake and cancels the reimbursement, there seems to be no way to reopen it or create a new reimbursement based on the travel support request.

Am I mistaken and i did not find how to do it?

Otherwise seems to be a bit harsh since people will make mistakes and if he can't fix them nor create a new reimbursement based on the travel support request means that we have to go, modify the travel support request last date for the event, he needs to create a new travel support request and then a reimbursement request, which all seems lot of work.

If there's no way to reopen a reimbursement i can try to fix it myself if you point me to the right direction.

**Comment by ancorgs** [comment]
A user with the supervisor role can change the status of any request/reimbursement with no need to follow the workflow.

**Comment by tsdgeos** [comment]
Ah, thanks, didn't find this anywhere :)
