### ISSUE TITLE
New feature: Add "Event organizer" concept

### ISSUE THREAD

**Issue by tsdgeos** [openSUSE/travel-support-program#31]
It would be very useful in KDE's implementation of travel-support-program to have the concept of "Event organizer".

This would be set per Event and would allow that particular person to see people that have signed up for that event.

Rationale: It happens often that event organizers need to chase their attendees to sign up because they forget, etc. By being able to see the people that have signed up (not the amount they have requested, but maybe if they have been approved or not) they can have help with this without having to bug someone from the tsp.

**Comment by krngrvr09** [comment]
Hey @ancorgs 
The reason for adding the 'Event Organizer' concept is to make it easier for them to see who have signed up for the event and their status. As far as I understand the application only records Travel Support Requests, Shipment Requests and Reimbursements. So the people related to an event are only those who have submitted a request and not all the people who have signed up for the event, is that right?

**Comment by tsdgeos** [comment]
What does "sign up for the event" mean if not "have submitted a request"?

**Comment by ancorgs** [comment]
@tsdgeos I guess @krngrvr09 means "people registered to the event", which is a superset of "people asking for support to attend to the event".

**Comment by krngrvr09** [comment]
Yes, I was just confirming if 'sign up for the event', in this context, means the same as 'have submitted a request'.

**Comment by tsdgeos** [comment]
> Yes, I was just confirming if 'sign up for the event', in this context, means the same as 'have submitted a request'.

Correct :)

**Comment by krngrvr09** [comment]
Hey @tsdgeos  and @ancorgs 
So I looked on this task. Here is my understanding on how to solve it.
This would involve creating a new Role. When a user creates an event, he/she will be assigned the default role of Event Organizer. After that the user can add/remove other event organizers. Basically, there can be multiple event organizers for the same event. I think the best way is to add permissions in such a way that event organizers(in addition to other authorized users) can see the status of requests for their events in the events page only. 

Is that correct?

**Comment by tsdgeos** [comment]
When you mean "new role" you mean site-wide role like tspmember? I don't think that makes sense, event organizer should be a per-event position.

About "the first user that creates an event gets organizer role", I am not convinced this is a good idea either, we have people registering events because they know they will happen (discussed at mailing list, etc) and the first one to create an event is not necessarily the one that is the organizer.

This meaning that unless we're very careful at monitoring every single time a new event is created, it could create a bit of a privacy problem since that person that is not the organizer (just the first person to register) could see more stuff than he really needs to. I personally prefer if only members of the tspmember role can add/remove the first event organizer (after that i don't mind if they can also add/remove new event organizers).

**Comment by krngrvr09** [comment]
Yes, that makes sense.
So the way I am seeing it now is: 
1. An event will have many Event Organizers. 
2. TSP members can add/remove an Event Organizer. Event Organizer can themselves add/remove among each other. This will be done on ``/events/<event_id>/`` page. 
3. The UI for selecting users for event organizers can be the same as when tagging people on github(with the dropdown). One will be able to search with both full name and nickname. 
4. Event Organizers will have permissions such that they will be able to see state of requests for their events on the Requests page itself. 
5.After doing that, tests will be required to check if everything works correctly.

Is that right?

**Comment by tsdgeos** [comment]
Makes sense to me

**Comment by ancorgs** [comment]
I agree with everything @tsdgeos said in the previous comment and I also agree the new suggested approach makes more sense.

We are talking about people asking for money here. It's very sensitive data, so new roles and permissions for those roles should be very well though.

**Comment by bgeuken** [comment]
@ancorgs @tsdgeos So event organizers have the right to send mails to event participants. Are there any additional rights an event organizer should have? Eg. should he be able to see or even write the budget?,

**Comment by bgeuken** [comment]
@ancorgs @tsdgeos Another thing we stumbled over is whether it makes sense to allow tsp_members to make any user known to TSP an organizer of a particular event.
We think this should be a valid scenario. Let's say someone should organize the event who did not yet requested travel support (or anything alike).

What do you say?

**Comment by tsdgeos** [comment]
@bgeuken Sure, the even organizer can be "anyone". Most of the times (at least for us) the organizer doesn't even request travel support since it's a person local to the city where the event happens.

**Comment by tsdgeos** [comment]
> Are there any additional rights an event organizer should have?

At least seeing the people that has applied for reimbursement and the status of their request. Personally i don't think seeing the requested amount is important here (i'd even say it's not desireable)

**Comment by bgeuken** [comment]
Alright. Thanks for the quick feedback:+1:

**Comment by nikhilgupta1211** [comment]
@tsdgeos we have implemented the event organizer concept can you please try it and gives us some feedback :)

You can try it on https://travel-support.herokuapp.com/

Log in as a tsp member, then go to an event and click on the organizers link
![image](https://user-images.githubusercontent.com/14905919/29285248-7c12c3f2-814b-11e7-9297-d4e9b6fc70d7.png)

Then go to add event organizer and search the user with the help of email and add it
![event_org](https://user-images.githubusercontent.com/14905919/29285286-a2f07ff0-814b-11e7-866e-6e31472cf3d4.png)

The event organizer can access the event email of the event and can see the participants of the event.

To view the participants of an event click on the participants link in the show view of an event.

**Comment by tsdgeos** [comment]
> Then go to add event organizer and search the user with the help of email and add it

Can we do it so it searches both email and username?

**Comment by tsdgeos** [comment]
Also, i'm getting an error while updating that says

ActionView::Template::Error (Mysql2::Error: Table 'reimbursements.event_organizers' doesn't exist: SHOW FULL FIELDS FROM `event_organizers`):

Is the database automatically updated or should i do something to get it updated?

**Comment by nikhilgupta1211** [comment]
@tsdgeos did you ran `rake db:migrate` after updating?

Also, we have added the functionality to search by both username and email for the event organizer. Please have a look at it :)

**Comment by tsdgeos** [comment]
Ok, that fixed it, but the page i get looks like i'm missing some CSS or thinks i'm on mobile or something
http://i.imgur.com/0N8jgvu.png
Any idea of what may be wrong?

**Comment by nikhilgupta1211** [comment]
@tsdgeos sorry for the late reply. Can you please tell if you used bundle install after updating ?

**Comment by tsdgeos** [comment]
Yes, http://paste.ubuntu.com/25354060/

**Comment by nikhilgupta1211** [comment]
Please try `rake assets:clean` and then `rake assets:precompile`

**Comment by tsdgeos** [comment]
that seems to have work, even though i got 
[warn]: Error loading plugin 'yard-activerecord'
messages.

Do you know how bad that is?

**Comment by nikhilgupta1211** [comment]
It is ok :)

Can you please also check the event organizer feature?

**Comment by tsdgeos** [comment]
Is it possible that you broke autocompletion? Using bad8a51c1a0abd4b5088d01831abb251c2613ae8 ifi write "aac" in the "Add an event organizer" i get nothing, using c12fe46e62b08ec45a5a88c9a351552f44baf19e i get my aacid@kde.org address autocompleted

**Comment by nikhilgupta1211** [comment]
@tsdgeos does it show a 'No existing match' message? If it doesn't then can you please share your terminal screenshot while using autocomplete.

Also can you please try it here http://travel-support.herokuapp.com/ you can type `com` to see most of the users :)

**Comment by tsdgeos** [comment]
> @tsdgeos does it show a 'No existing match' message? 

No, shows nothing http://i.imgur.com/ksPbke4.png

> If it doesn't then can you please share your terminal screenshot while using autocomplete.

You lost me here, i guess you're not refering to my actual laptop terminal right? How would that matter?

> Also can you please try it here http://travel-support.herokuapp.com/ you can type com to see most of the users :)

Yes, that works

**Comment by ancorgs** [comment]
As far as I know, this is fully working in recent versions. Feel free to reopen if that's not the case.
