### ISSUE TITLE
New feature: Add "Send email to event" ability

### ISSUE THREAD

**Issue by tsdgeos** [openSUSE/travel-support-program#32]
It is sometimes very useful to send a wholesale email to everyone that is registered/attending a given event to communicate with them.

I see this feature could be implemented in the "event view" for tsp members and ideally would let you choose to whom the email is sent, i.e. all attendants, or per state (those who are incomplete, those who are submited, etc) like you can do in the "travel support requets" view.

**Comment by ancorgs** [comment]
@tsdgeos Have you considered a GSoC of project for the TSP app? We could include this and also https://github.com/openSUSE/travel-support-program/issues/31 and maybe others things you miss (UI improvements, integration with whatever...).

I will most likely mentor a couple of projects in the openSUSE organization related to YaST and to Jangouts, which leaves me relatively little time for the administrative part of just another GSoC project, but I would happily offer assistance with this or would co-mentor.

**Comment by tsdgeos** [comment]
Yeah, thought about it, but would need a mentor that knows some ruby on rails, the little i can do is totally copy&paste some stuff :D

**Comment by ancorgs** [comment]
@tsdgeos I forgot to mention. We finally found a co-mentor and we are offering this as an idea for GSoC at https://101.opensuse.org. Maybe you want to promote it or to replicate the idea in the KDE organization.

See https://github.com/openSUSE/mentoring/issues/78

**Comment by tsdgeos** [comment]
Awesome :+1: 

I'll tell our GSoC guys

**Comment by krngrvr09** [comment]
@tsdgeos After looking at this task, I think the right way would be to 
1. Provide a button in the events page to send an email. The button will only be visible to TSP members. 2. On clicking on that button, a modal will open for composing the email. 
3. The user can select individual recepients the same way we tag users on Github. And there will be also checkboxes to select a set of people together based on their request status.
4. After sending the email there will be checks in the backend to enforce permissions. Just because one cannot see the mailing button, doesnt mean they cannot send one.
5. We could consider something like subscribing to emails but I feel that's for the future.
6. Ofcourse tests would be required for this feature as well.

I feel the challenging part would be implementing the UI for selecting recepients so that it is most useful and unambiguous. I can think of a case where a TSP member selects all users with requests that are approved, and then adds another recipient individually that overlaps with that list. We should make it obvious that the lists will be merged and the mail wont be sent twice.

What do you think?

**Comment by tsdgeos** [comment]
I think button should be available to "This Event Organizers" too (once that other feature is implemented)

To be honest i do not see the use case for adding people individually, you normally would want to email "everyone" or "the ones that have still not submitted their request", so i think if that is going to be a "problem" UI wise, we can at least skip it for the firs implementation

**Comment by krngrvr09** [comment]
Sure! That makes sense! I'll update this information in [my proposal](https://docs.google.com/document/d/17DUCoBhc-KePllKhzkkEzBNhdunhgcIzqOCaZFHH8rQ/edit?usp=sharing). It would be great if you could give me some feedback on the current draft. 
I would love to hear if you have any new features/changes in mind that can be applied to TSP Application or if you think I should change my approach towards some of the tasks.

Thank you for your valuable feedback up till now. :)

**Comment by krngrvr09** [comment]
Hey @ancorgs 
Can you have a look at the proposal again? I have incorporated the feedback that you mailed me.

If you could help me out with my approach for moving permissions and notifications to a configuration file, that would be great :)

Thank you

**Comment by bgeuken** [comment]
Hi @tsdgeos,
@nikhilgupta1211 implemented a first version of this in #54. Would be great if you could check it out and give us some feedback.

We currently consider to add additional features like a html or markdown editor support and tracking sent mails, eg. having a list overview.

**Comment by tsdgeos** [comment]
I'll try to have a look soon, but i'm on holiday wednesday-sunday so it may take a while. Thanks for the work :)

**Comment by tsdgeos** [comment]
Aaaaaaaaaaaaaaaaaand i've broken our installation trying to update to the new code, i've requested for help from our sysadmins, sorry it's taking more that expected to give feedback

**Comment by nikhilgupta1211** [comment]
@tsdgeos you can check the feature at https://travel-support.herokuapp.com/  :)

**Comment by tsdgeos** [comment]
I can't, i guess because i'm just a plain user.

Did you add the "person that organizes this particular event" concept? Or just tsp members have the hability to send emails to even attendees?

**Comment by nikhilgupta1211** [comment]
We are working on the event organizer feature and currenlty TSP members can only use the email facility.
Please try using it with the help of :

username: tspmember@example.com
password: tspmember1

**Comment by tsdgeos** [comment]
Can the "Select recipients" be a non exclusive selection? 

I mean i may want to email Accepted and Approved

**Comment by ChrisBr** [comment]
@tsdgeos thanks for your feedback! That makes totally sense!

**Comment by bgeuken** [comment]
@tsdgeos That's implemented now:-)

**Comment by nikhilgupta1211** [comment]
@tsdgeos we have added a markdown preview option in the event email. Please have a look, thank you :)

You can try it at https://travel-support.herokuapp.com/

**Comment by tsdgeos** [comment]
Looks nice :)
