### ISSUE TITLE
Events description doesn't respect formatting of the form

### ISSUE THREAD

**Issue by tsdgeos** [openSUSE/travel-support-program#33]
The form contents are

>This Plasma sprint will be hosted at von foobar.
>
>From Stuttgart Hauptbahnhof (main station) it is a less than 10 minutes walk to get there.

but the displaying is

> This Plasma sprint will be hosted at von foobar. From Stuttgart Hauptbahnhof (main station) it is a less than 10 minutes walk to get there.

It would be nice if the display respected the formatting (basically paragraphs) of the form.

**Comment by ancorgs** [comment]
Sorry. I overlooked this (too many notifications coming from github). I'll try to take a look ASAP

**Comment by ancorgs** [comment]
But don't take "ASAP" too seriously. :-/
