### ISSUE TITLE
Add a preview view to the event emails

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/travel-support-program#60]
We are having markdown support now for event mails. It would be nice to allow users to see a preview of the email the are writing.

**Comment by nikhilgupta1211** [comment]
It is really a good Idea. I tried to implement it but as we are using Redcarpet for markdown we have to make the preview part with the help of ajax or we can use some javascript plugin for markdown and then make the preview that way we will have everything at the client side which will be faster, so can you please tell which approch should we go with ?

**Comment by ChrisBr** [comment]
I think implementing it with ajax is fine as otherwise it could happen that we have different markdown interpretations on frontend and backend. @nikhilgupta1211

**Comment by nikhilgupta1211** [comment]
No actually I was suggesting to use a different markdown instead of Redcarpet on both frontend and backend.
