### ISSUE TITLE
Document markdown support of event emails

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/travel-support-program#61]
We should document the markdown support we have now for event mails.

This should cover the markdown syntax we support.

**Comment by ChrisBr** [comment]
Yes, and please introduce a message that markdown is supported on the event_emails#new site.

**Comment by nikhilgupta1211** [comment]
We can close this issue as it has been resolved by #72  :)

**Comment by ChrisBr** [comment]
Right :+1:
