### ISSUE TITLE
Body on event_emails#index is not markdown

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/travel-support-program#68]
https://github.com/openSUSE/travel-support-program/blob/master/app/views/event_emails/index.html.haml#L18

**Comment by bgeuken** [comment]
Did you try this in the ui? I've seen this working. It seems to be fine in [our heroku instance](https://travel-support.herokuapp.com/events/160780002/event_emails/717280376) as well.

Or am I looking at the wrong spot?
