### ISSUE TITLE
Wrong permission check for changin event dates(?)

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/travel-support-program#84]
It looks like any logged in user can change the dates of an event.

To reproduce create an account go the the event list and select an event. Now click on edit, change the dates and save it.

**Comment by nikhilgupta1211** [comment]
@bgeuken please check if that event is validated or not. Events which are not validated can be editted by other users.

**Comment by bgeuken** [comment]
Ah, you are right! Sorry for the noise
